version: '2.3'
services:
  babycamproxy:
    image: kverhaar/kv-webcam-proxy:1.1
    cpus: 0.2
    environment:
      - WEBCAMPROXY_DESTHOST=${BABYCAM_HOST}
    networks:
      - default
  motioneye:
    image: ccrisan/motioneye:0.39.3-amd64
    cpus: 0.5
    ports:
      - 8765:8765
      - 8081:8081
    environment:
      - HA_TOKEN=${HA_TOKEN}
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/home/kees/config/motioneye:/etc/motioneye"
      - "/home/kees/data/motioneye:/var/lib/motioneye"
  homeassistant:
    image: homeassistant/home-assistant:0.84.6
    cpus: 1.5
    depends_on:
      hass-db:
        condition: service_healthy
      mosquitto:
        condition: service_started
      influxdb:
        condition: service_healthy
    volumes:
      - "/home/kees/homeassistant:/config"
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    ports:
      - 8123:8123
    networks:
      - traefik_proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.backend=homeassistant"
      - "traefik.frontend.rule=Host:home.${DOMAINNAME}"
      - "traefik.port=8123"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=deverhaartjes.nl"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    cpus: 0.2
    volumes:
      - "/home/kees/config/zigbee2mqtt:/app/data"
    devices:
      - "/dev/ttyACM1:/dev/ttyACM1"
  appdaemon:
    image: acockburn/appdaemon:3.0.2
    cpus: 0.2
    depends_on:
      - homeassistant
    environment:
      - HA_URL=http://homeassistant:8123
      - DASH_URL="http://home.lan:5050"
      - TOKEN=${HA_TOKEN}
    volumes:
      - "/home/kees/appdaemon:/conf"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=appdaemon"
      - "traefik.frontend.rule=Host:appdaemon.${DOMAINNAME}"
      - "traefik.frontend.auth.basic.usersFile=/shared/.htpasswd"
      - "traefik.port=5050"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=deverhaartjes.nl"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
    networks:
      - default
      - traefik_proxy
  hass-db:
    image: postgres:10
    cpus: 0.2
    volumes:
      - /home/kees/data/homeassistant:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${HA_POSTGRES_USER}
      - POSTGRES_PASSWORD=${HA_POSTGRES_PASSWORD}
      - POSTGRES_DB=homeassistant
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 6
    networks:
      - default
  influxdb:
    image: influxdb:1.6
    cpus: 0.2
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/home/kees/config/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro"
      - "/home/kees/data/influxdb:/var/lib/influxdb"
    healthcheck:
      test: ["CMD-SHELL", "curl -sI http://127.0.0.1:8086/ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 6
    networks:
      - default
      - influxdb
  mosquitto:
    image: eclipse-mosquitto:1.5
    cpus: 0.3
    ports:
      - "1883:1883"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/home/kees/config/mosquitto:/mosquitto/config"
      - "/home/kees/data/mosquitto/log:/mosquitto/log"
      - "/home/kees/data/mosquitto/data:/mosquitto/data"
    # healthcheck:
    #   test: ["CMD-SHELL", "mosquitto_sub -t '$$SYS/#' -C 1 | grep -v Error || exit 1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 6
    networks:
      - default
  node-red:
    image: nodered/node-red-docker:v8
    cpus: 0.2
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/home/kees/config/node-red:/data"
    environment:
      - FLOWS=flows.json
    networks:
      - default
      - traefik_proxy
    depends_on:
      - mosquitto
    labels:
      - "traefik.enable=true"
      - "traefik.backend=node-red"
      - "traefik.frontend.rule=Host:node-red.${DOMAINNAME}"
      - "traefik.frontend.auth.basic.usersFile=/shared/.htpasswd"
      - "traefik.port=1880"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=deverhaartjes.nl"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
  traccar:
    image: traccar/traccar:4.2
    cpus: 0.2
    volumes:
      - "/home/kees/config/traccar/logs:/opt/traccar/logs:rw"
      - "/home/kees/config/traccar/traccar.xml:/opt/traccar/conf/traccar.xml:ro"
    networks:
      - default
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traccar"
      - "traefik.frontend.rule=Host:traccar.${DOMAINNAME}"
      - "traefik.port=8082"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=deverhaartjes.nl"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=false"
  traccar-db:
    image: kverhaar/postgres:10
    cpus: 0.2
    volumes:
      - /home/kees/data/traccar:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${TRACCAR_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TRACCAR_POSTGRES_PASSWORD}
      - POSTGRES_DB=traccar
    networks:
      - default
networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  influxdb:
    external:
      name: influxdb
  default:
    driver: bridge
