version: '3'
services:
  pihole:
    image: pihole/pihole:4.0.0-1_amd64
    restart: always
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/home/kees/config/pihole/pihole/:/etc/pihole/"
      - "/home/kees/config/pihole/dnsmasq.d/:/etc/dnsmasq.d/"
    dns:
      - 127.0.0.1
      - 192.168.1.1
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.backend=grafana"
    #   - "traefik.frontend.rule=Host:grafana.${DOMAINNAME}"
    #   - "traefik.port=3000"
    #   - "traefik.docker.network=traefik_proxy"
    #   - "traefik.frontend.headers.SSLRedirect=true"
    #   - "traefik.frontend.headers.STSSeconds=315360000"
    #   - "traefik.frontend.headers.browserXSSFilter=true"
    #   - "traefik.frontend.headers.contentTypeNosniff=true"
    #   - "traefik.frontend.headers.forceSTSHeader=true"
    #   - "traefik.frontend.headers.SSLHost=deverhaartjes.nl"
    #   - "traefik.frontend.headers.STSIncludeSubdomains=true"
    #   - "traefik.frontend.headers.STSPreload=true"
    #   - "traefik.frontend.headers.frameDeny=true"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80"
      - "443:443"
    environment:
      - ServerIP=192.168.1.22
      - TZ=Europe/Amsterdam
      - WEBPASSWORD=${PIHOLE_PASSWORD}
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://127.0.0.1:3000/login || exit 1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 6
    networks:
      - default
     
networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  monitor-net:
    external:
      name: monitor-net
  default:
