version: '2.3'
services:
  sickrage:
    image: linuxserver/sickrage:153
    cpus: 0.4
    volumes:
      #- "/home/kees/data/sickrage:/data"
      - "/home/kees/data/sickchill:/config"
      - "/etc/localtime:/etc/localtime:ro"
      - "/mnt/video/Series:/tv"
      - "/mnt/downloads/SABnzbd/Downloads/sickrage:/downloads"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=sickrage"
      - "traefik.frontend.rule=Host:sickrage.${DOMAINNAME}"
      - "traefik.frontend.auth.basic.usersFile=/shared/.htpasswd"
      - "traefik.port=8081"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=deverhaartjes.nl"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
    networks:
      - traefik_proxy
      - default
  sabnzbd:
    image: "sabnzbd/sabnzbd"
    volumes:
      - "/home/kees/data/sabnzbd:/datadir"
      - "/mnt/downloads/SABnzbd/Downloads:/media"
    environment:
      - SABNZBD_UID=100
      - SABNZBD_GID=100
    ports:
      - "8080:8080"
    networks:
      - default
networks:
  default:
  traefik_proxy:
    external:
      name: traefik_proxy